### ISSUE TITLE
Problem running "HippocampalPlaceCellExample" script

### ISSUE THREAD

**Issue by brykko** [cajigaslab/nSTAT#1]
Hi,

I just tried to run the "HippocampalPlaceCellExample" script, using the example data that I just got from here: https://figshare.com/articles/data_zip/4834640

I encounter an error, here's the stack trace:

```
Reference to non-existent field 'xlabelval'.

Error in nspikeTrain.fromStructure (line 800)
            xlabelval  = structure.xlabelval;

Error in FitResult.fromStructure (line 1455)
                    spikeObj=nspikeTrain.fromStructure(structure.neuralSpikeTrain);

Error in FitResult.fromStructure (line 1475)
                  fitObj{i} = FitResult.fromStructure(structure{i});

Error in HippocampalPlaceCellExample (line 102)
    results = FitResult.fromStructure(resData.resStruct);
```

It looks like the ```nspikeTrain.fromStructure``` method requires several fields that are absent in the loaded "neuralSpikeTrain" structure, specifically these ones: ```'xlabelval', 'xunits', 'yunits', 'dataLabels'```.

**Comment by iahncajigas** [comment]
Thank you for pointing out this issue and for using nSTAT. It has been resolved in the version updated today. Please also download the new data from figshare.
