### ISSUE TITLE
FitResult.fromStructure error

### ISSUE THREAD

**Issue by brykko** [cajigaslab/nSTAT#2]
Hi,

I had en error in the FitResult.fromStructure method, and noticed that the arguments that the method passes to the FitResult constructor differ from the contructor signature (the "logLL" argument is missing).

FitResult constructor:
```matlab
function fitObj=FitResult(spikeObj,covLabels,numHist,histObjects,ensHistObj,lambda,b, dev, stats,AIC,BIC,logLL, configColl,XvalData,XvalTime,distribution)
```
Constructor call in FitResult.fromStructure:
```matlab
fitObj=FitResult(spikeObj,structure.covLabels,structure.numHist,histObjects,ensHistObject,lambda,structure.b, structure.dev, structure.stats,structure.AIC,structure.BIC,configColl,structure.XvalData,structure.XvalTime,structure.fitType);
```

**Comment by iahncajigas** [comment]
Thank you for pointing out this issue and for using nSTAT. It has been resolved in the version updated today. Please also download the new data from figshare.
